app_resource_group = "TwitchApp-TEST-RG"
app_service_plan = "twitchapp-test-serviceplan"
app_service_linux_web_app = "twitchapp-test-app"
docker_image = "dmctwitchacr.azurecr.io/twitchappdemo"
docker_image_tag = "test"
aspnetcore_envrionment = "Test"