name: "App Service Build and Deploy"

on:
  push:
    branches:
      - main
      - releases/**
    paths:
      - 'TwitchAppDemo/**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
  docker_image_build:
    name: "Docker Image Build"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TwitchAppDemo
    
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Login Via Azure CLI'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image
        id: build-image
        run: |
          az acr build --image ${{ secrets.REGISTRY_LOGIN_SERVER}}/twitchappdemo:${{ github.run_number }} --registry ${{ secrets.REGISTRY_LOGIN_SERVER }} --file "Dockerfile" .
          
      - name: Set output parameter
        id: image_name
        run: echo "::set-output name=image::$REGISTRY_LOGIN_SERVER/twitchappdemo:${{ github.run_number }}"

  deploy_to_dev:
    name: "Deploy to Dev"
    needs: docker_image_build
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v2
        with:
          app-name: twitchapp01-app
          images: ${{ needs.docker_image_build.outputs.image_name }}

      - name: Azure logout
        run: az logout
    
  deploy_to_test:
    name: "Deploy to Test"
    needs: [ docker_image_build, deploy_to_dev ]
    environment: Test
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v2
        with:
          app-name: twitchapp01-app
          images: ${{ needs.docker_image_build.outputs.image_name }}

      - name: Azure logout
        run: az logout

  deploy_to_prod:
    name: "Deploy to Prod"
    needs: [ docker_image_build, deploy_to_dev, deploy_to_test ]
    environment: Prod
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v2
        with:
          app-name: twitchapp01-app
          images: ${{ needs.docker_image_build.outputs.image_name }}

      - name: Azure logout
        run: az logout