name: 'Infrastructure Deployment'
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  Plan_Dev:
    uses: dylan-mccarthy/TwitchSteamAppService/.github/workflows/tf-plan.yaml@main
    with:
      gh_environment: Dev
      tf_vars_file: dev.tfvars
      path: ./Infra/dev
    secrets:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  Apply_Dev:
    needs: Plan_Dev
    uses: dylan-mccarthy/TwitchSteamAppService/.github/workflows/tf-apply.yaml@main
    with:
      gh_environment: Dev
      path: ./Infra/dev
  Plan_Test:
    needs: [Plan_Dev,Apply_Dev]
    uses: dylan-mccarthy/TwitchSteamAppService/.github/workflows/tf-plan.yaml@main
    with:
      gh_environment: Test
      tf_vars_file: test.tfvars
      path: ./Infra/test
    secrets:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  Apply_Test:
    needs: Plan_Test
    uses: dylan-mccarthy/TwitchSteamAppService/.github/workflows/tf-apply.yaml@main
    with:
      gh_environment: Test
      path: ./Infra/test
  Plan_Prod:
    needs: [Plan_Test, Apply_Test]
    uses: dylan-mccarthy/TwitchSteamAppService/.github/workflows/tf-plan.yaml@main
    with:
      gh_environment: Prod
      tf_vars_file: prod.tfvars
      path: ./Infra/prod
    secrets:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  Apply_Prod:
    needs: Plan_Prod
    uses: dylan-mccarthy/TwitchSteamAppService/.github/workflows/tf-apply.yaml@main
    with:
      gh_environment: Prod
      path: ./Infra/prod