name: "Nightly Build"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build:
    name: "Nightly Build"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TwitchAppDemo
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: "Setup .NET 7.0"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0

      - name: "DotNet Restore"
        run: dotnet restore
      
      - name: "DotNet Build"
        run: dotnet build --configuration Release